/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardIndexRouteImport } from './routes/board.index'
import { Route as RegistryItemIdRouteImport } from './routes/registry.$itemId'
import { Route as BoardNominateRouteImport } from './routes/board.nominate'
import { Route as BoardItemIdRouteImport } from './routes/board.$itemId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryItemIdRoute = RegistryItemIdRouteImport.update({
  id: '/registry/$itemId',
  path: '/registry/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardNominateRoute = BoardNominateRouteImport.update({
  id: '/board/nominate',
  path: '/board/nominate',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardItemIdRoute = BoardItemIdRouteImport.update({
  id: '/board/$itemId',
  path: '/board/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/board/$itemId': typeof BoardItemIdRoute
  '/board/nominate': typeof BoardNominateRoute
  '/registry/$itemId': typeof RegistryItemIdRoute
  '/board/': typeof BoardIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/board/$itemId': typeof BoardItemIdRoute
  '/board/nominate': typeof BoardNominateRoute
  '/registry/$itemId': typeof RegistryItemIdRoute
  '/board': typeof BoardIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/board/$itemId': typeof BoardItemIdRoute
  '/board/nominate': typeof BoardNominateRoute
  '/registry/$itemId': typeof RegistryItemIdRoute
  '/board/': typeof BoardIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/board/$itemId'
    | '/board/nominate'
    | '/registry/$itemId'
    | '/board/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/board/$itemId'
    | '/board/nominate'
    | '/registry/$itemId'
    | '/board'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/board/$itemId'
    | '/board/nominate'
    | '/registry/$itemId'
    | '/board/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BoardItemIdRoute: typeof BoardItemIdRoute
  BoardNominateRoute: typeof BoardNominateRoute
  RegistryItemIdRoute: typeof RegistryItemIdRoute
  BoardIndexRoute: typeof BoardIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/': {
      id: '/board/'
      path: '/board'
      fullPath: '/board/'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$itemId': {
      id: '/registry/$itemId'
      path: '/registry/$itemId'
      fullPath: '/registry/$itemId'
      preLoaderRoute: typeof RegistryItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/nominate': {
      id: '/board/nominate'
      path: '/board/nominate'
      fullPath: '/board/nominate'
      preLoaderRoute: typeof BoardNominateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$itemId': {
      id: '/board/$itemId'
      path: '/board/$itemId'
      fullPath: '/board/$itemId'
      preLoaderRoute: typeof BoardItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BoardItemIdRoute: BoardItemIdRoute,
  BoardNominateRoute: BoardNominateRoute,
  RegistryItemIdRoute: RegistryItemIdRoute,
  BoardIndexRoute: BoardIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
